import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer' 
import Navbar from '../components/Navbar'
import { ParallaxBanner, ParallaxBannerLayer, Parallax } from 'react-scroll-parallax'
import React, { useRef, useState } from 'react'
import InfoCard from '../components/InfoCard'
import Skills from '../components/Skills'

export default function Home() {
  const target = useRef()
  const infoDiv = useRef()
  const mainBanner = useRef()
  const [infoDivActive, setInfoDivActive] = useState(false)

  return (
    <div ref={target} className='${styles.container} flex h-fitcontent justify-center flex-col bg-gradient-to-b from-color5 via-color1/50 to-color2 text-color2 overflow-hidden'>
      <Head>
        <title>Tim Rathert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`lg:w-2/3 lg:self-center`}>
      <ParallaxBanner
        className="aspect-[2/1] h-[40rem] mb-32 "
        strength={800}
        ref = {mainBanner}
        layers={[
          // {
          //   children: <figure className = {`bg-color6 w-full h-screen`}></figure>
          // },

          {       
            children: 
            <Image src='/sky.jpg' width='100%' height='100%' layout='fill' className={'sepia-[30%]'}/>,
            expanded: false,
            speed: -20,
          },
          {       
            children: 
            <figure className={'bg-gradient-radial sepia-[40%] from-color1 to-white aspect-square h-2/5 rounded-full shadow-[5px_5px_10px_rgba(255,255,255,0.2)] before:bg-gradient-radial3 before:blur-lg '}>
              <span className={`bg-gradient-radial2 absolute`}></span>
            </figure>,
            expanded: false,
            speed: -35,
            scale: [1.4, 1],
            opacity: [3, 0.1], 
            translateY:[-80,80],
            translateX:[80,40],
            rotateX:[30,-0],
            
          },
          {       
            children: <Image src="/mountains.png" width='100%' height='100%' layout='fill' className={'mt-24'}/>,
            expanded: false,
            speed: -10,
            scale: [1, 1.4],
            opacity: [2, 1], 
          },
          {
            children: <div className={`text-color1/50 text-5xl text-center -skew-x-12 -scale-y-100 scale-y-50 opacity-5 motion-safe:animate-pulse`}>Hello World</div>,
            expanded: false,
            speed: 30,
            scale: [.6, 1.4],
            opacity: [1, .1],
            translateY:[85,105],
          },
          {
            children: <div className={`text-5xl text-center motion-safe:animate-pulse `}>Hello World</div>,
            expanded: false,
            speed: 30,
            scale: [.6, 1.4],
            opacity: [1, .1],
            translateY:[65,105],
          },
          {
            /* opacity layer */
            opacity: [-0.2, 1],
            shouldAlwaysCompleteAnimation: true,
            expanded: false,
            children: (
              <div className="absolute inset-0 bg-gradient-to-t from-gray-900 to-color6" />
            ),
          }
        ]}
      />
      <Parallax 
        targetElement={infoDiv.current} 
        onEnter={()=>{setInfoDivActive(!infoDivActive)}} 
        onExit={()=>{setInfoDivActive(!infoDivActive)}} 
        speed={-15} 
        className={`flex justify-center`}
        translateX={['90vw','-90vw']}
        >
          <div className={`info w-5/6 h-8 my-2 transition-all bg-color5 duration-[2000] lg:w-full ${infoDivActive ? 'opacity-100' : 'opacity-0'} rounded-2xl shadow-[5px_5px_10px_rgba(0,0,0,0.3)]`}> 
          </div>
      </Parallax>
      <Parallax 
        targetElement={infoDiv.current} 
        onEnter={()=>{setInfoDivActive(!infoDivActive)}} 
        onExit={()=>{setInfoDivActive(!infoDivActive)}} 
        speed={-10} 
        className={`flex justify-center`}
        translateX={['-100vw','90vw']}
        >
          <div className={`info w-5/6 h-8 my-2 transition-all bg-color4 duration-[2000] lg:w-full ${infoDivActive ? 'opacity-100' : 'opacity-0'} rounded-2xl shadow-[5px_5px_10px_rgba(0,0,0,0.3)]`}> 
          </div>
      </Parallax>
      <Parallax 
        targetElement={infoDiv.current} 
        onEnter={()=>{setInfoDivActive(!infoDivActive)}} 
        onExit={()=>{setInfoDivActive(!infoDivActive)}} 
        speed={-5} 
        className={`flex justify-center`}
        translateX={['90vw','-110vw']}
        >
          <div className={`info w-5/6 h-8 my-2 transition-all duration-[2000] bg-color3 lg:w-full ${infoDivActive ? 'opacity-100' : 'opacity-0'} rounded-2xl shadow-[5px_5px_10px_rgba(0,0,0,0.3)]`}> 
          </div>
      </Parallax>
      <Parallax 
        targetElement={infoDiv.current} 
        onEnter={()=>{setInfoDivActive(!infoDivActive)}} 
        onExit={()=>{setInfoDivActive(!infoDivActive)}} 
        speed={-2} 
        className={`flex justify-center`}
        translateX={['-120vw','90vw']}
        >
          <div className={`info w-5/6 h-8 my-2 transition-all bg-color2 duration-[2000] lg:w-full ${infoDivActive ? 'opacity-100' : 'opacity-0'} rounded-2xl shadow-[5px_5px_10px_rgba(0,0,0,0.3)]`}> 
          </div>
      </Parallax>

      <InfoCard infoDiv = {infoDiv}/>
        <Parallax
          speed={25}
          translateY={['100px','0px']}>
        </Parallax>
      
      <Parallax
        targetElement={infoDiv.current}
        speed={-5}
        scale={[0,1]}
        >
          <Skills />
      </Parallax>



      </main>

      <Footer />

    </div>
  )
}
